#!/usr/bin/env bash
#
# 09-install-macos-app.sh — Build a macOS .app bundle that launches Steam
# with the v0.6 configuration (DXMT fork + virtual desktop + compat scrub).
#
# The .app is a thin AppleScript-free wrapper whose only job is to invoke
# `scripts/launch-steam.sh --detach` from the same repository. Because
# launch-steam.sh already handles prefix detection, wrapper reinstallation,
# compat-flag scrubbing and the virtual desktop, the .app itself stays a
# few KB and has no runtime state of its own.
#
# Where it lands
# --------------
#   Default: $HOME/Applications/Steam on M1 Wine.app
#   Override: INSTALL_APP_DIR=/elsewhere scripts/09-install-macos-app.sh
#
# Once installed, drag the app from ~/Applications into the Dock to pin it;
# clicking it boots Steam with the full stack in one tap.

# shellcheck source=lib/common.sh
source "$(dirname "$0")/lib/common.sh"
require_macos_arm64

APP_NAME="Steam on M1 Wine.app"
INSTALL_APP_DIR="${INSTALL_APP_DIR:-$HOME/Applications}"
APP_PATH="$INSTALL_APP_DIR/$APP_NAME"
VERSION="${STEAM_ON_M1_WINE_VERSION:-0.6}"

log_step "Installing $APP_NAME to $INSTALL_APP_DIR"

mkdir -p "$APP_PATH/Contents/MacOS"
mkdir -p "$APP_PATH/Contents/Resources"

# -- Info.plist ---------------------------------------------------------------
# Minimum viable set of keys for a GUI app:
#   CFBundleExecutable tells Launch Services which binary inside MacOS/ to run
#   CFBundleIdentifier is the reverse-DNS ID the system uses for per-app state
#   CFBundlePackageType=APPL marks this as an application bundle
cat > "$APP_PATH/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>launcher</string>
    <key>CFBundleIdentifier</key>
    <string>com.github.notpop.steam-on-m1-wine</string>
    <key>CFBundleName</key>
    <string>Steam on M1 Wine</string>
    <key>CFBundleDisplayName</key>
    <string>Steam on M1 Wine</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>$VERSION</string>
    <key>CFBundleVersion</key>
    <string>$VERSION</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
PLIST

# -- launcher -----------------------------------------------------------------
# When Launch Services starts a .app it exec()s the binary named by
# CFBundleExecutable with no stdout/stderr, no controlling terminal, and a
# working directory of "/". We therefore:
#   - pin every subsequent path to $REPO_ROOT explicitly
#   - tee launch-steam.sh's own output into a log next to the temp files
#     the script already uses, so failures are debuggable from a crash
#     report
cat > "$APP_PATH/Contents/MacOS/launcher" <<LAUNCHER
#!/usr/bin/env bash
# Auto-generated by scripts/09-install-macos-app.sh — do not edit by hand.
# Regenerate from the repo with the same script to pick up changes.
set -e

REPO_ROOT="$REPO_ROOT"
LOG_FILE="/tmp/steam-on-m1-wine-launcher.log"

{
    printf '\n== %s boot via %s.app ==\n' "\$(date '+%F %T')" "Steam on M1 Wine"
    exec "\$REPO_ROOT/scripts/launch-steam.sh" --detach
} >>"\$LOG_FILE" 2>&1
LAUNCHER
chmod +x "$APP_PATH/Contents/MacOS/launcher"

log_ok "Installed at $APP_PATH"
log_info "Size: $(du -sh "$APP_PATH" | awk '{print $1}')"
log_info ""
log_info "To pin it to the Dock:"
log_info "  1. open $INSTALL_APP_DIR"
log_info "  2. Drag '$APP_NAME' onto the Dock"
log_info ""
log_info "Click the Dock icon to start Steam with the v$VERSION stack."
log_info "Runtime logs are appended to /tmp/steam-on-m1-wine-launcher.log"
